// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package dbsqlc

import (
	"context"
)

const createInvoice = `-- name: CreateInvoice :exec
INSERT INTO invoices (id, invoice_number, client_id, status, issue_date, due_date, subtotal, tax_total, total, amount_paid, currency, notes, template_id, pdf_path, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInvoiceParams struct {
	ID            string `json:"id"`
	InvoiceNumber string `json:"invoice_number"`
	ClientID      string `json:"client_id"`
	Status        string `json:"status"`
	IssueDate     string `json:"issue_date"`
	DueDate       string `json:"due_date"`
	Subtotal      int64  `json:"subtotal"`
	TaxTotal      int64  `json:"tax_total"`
	Total         int64  `json:"total"`
	AmountPaid    int64  `json:"amount_paid"`
	Currency      string `json:"currency"`
	Notes         string `json:"notes"`
	TemplateID    string `json:"template_id"`
	PdfPath       string `json:"pdf_path"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, createInvoice,
		arg.ID,
		arg.InvoiceNumber,
		arg.ClientID,
		arg.Status,
		arg.IssueDate,
		arg.DueDate,
		arg.Subtotal,
		arg.TaxTotal,
		arg.Total,
		arg.AmountPaid,
		arg.Currency,
		arg.Notes,
		arg.TemplateID,
		arg.PdfPath,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = ?
`

func (q *Queries) DeleteInvoice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, invoice_number, client_id, status, issue_date, due_date, subtotal, tax_total, total, amount_paid, currency, notes, template_id, pdf_path, created_at, updated_at FROM invoices WHERE id = ?
`

func (q *Queries) GetInvoice(ctx context.Context, id string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.AmountPaid,
		&i.Currency,
		&i.Notes,
		&i.TemplateID,
		&i.PdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, invoice_number, client_id, status, issue_date, due_date, subtotal, tax_total, total, amount_paid, currency, notes, template_id, pdf_path, created_at, updated_at FROM invoices WHERE invoice_number = ?
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.AmountPaid,
		&i.Currency,
		&i.Notes,
		&i.TemplateID,
		&i.PdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, invoice_number, client_id, status, issue_date, due_date, subtotal, tax_total, total, amount_paid, currency, notes, template_id, pdf_path, created_at, updated_at FROM invoices ORDER BY created_at DESC
`

func (q *Queries) ListInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxTotal,
			&i.Total,
			&i.AmountPaid,
			&i.Currency,
			&i.Notes,
			&i.TemplateID,
			&i.PdfPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByClient = `-- name: ListInvoicesByClient :many
SELECT id, invoice_number, client_id, status, issue_date, due_date, subtotal, tax_total, total, amount_paid, currency, notes, template_id, pdf_path, created_at, updated_at FROM invoices WHERE client_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByClient(ctx context.Context, clientID string) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxTotal,
			&i.Total,
			&i.AmountPaid,
			&i.Currency,
			&i.Notes,
			&i.TemplateID,
			&i.PdfPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByStatus = `-- name: ListInvoicesByStatus :many
SELECT id, invoice_number, client_id, status, issue_date, due_date, subtotal, tax_total, total, amount_paid, currency, notes, template_id, pdf_path, created_at, updated_at FROM invoices WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByStatus(ctx context.Context, status string) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxTotal,
			&i.Total,
			&i.AmountPaid,
			&i.Currency,
			&i.Notes,
			&i.TemplateID,
			&i.PdfPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceAmountPaid = `-- name: UpdateInvoiceAmountPaid :exec
UPDATE invoices SET amount_paid = ?, updated_at = ? WHERE id = ?
`

type UpdateInvoiceAmountPaidParams struct {
	AmountPaid int64  `json:"amount_paid"`
	UpdatedAt  string `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateInvoiceAmountPaid(ctx context.Context, arg UpdateInvoiceAmountPaidParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoiceAmountPaid, arg.AmountPaid, arg.UpdatedAt, arg.ID)
	return err
}

const updateInvoicePDFPath = `-- name: UpdateInvoicePDFPath :exec
UPDATE invoices SET pdf_path = ?, updated_at = ? WHERE id = ?
`

type UpdateInvoicePDFPathParams struct {
	PdfPath   string `json:"pdf_path"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateInvoicePDFPath(ctx context.Context, arg UpdateInvoicePDFPathParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoicePDFPath, arg.PdfPath, arg.UpdatedAt, arg.ID)
	return err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoices SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateInvoiceStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoiceStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateInvoiceTotals = `-- name: UpdateInvoiceTotals :exec
UPDATE invoices SET subtotal = ?, tax_total = ?, total = ?, updated_at = ? WHERE id = ?
`

type UpdateInvoiceTotalsParams struct {
	Subtotal  int64  `json:"subtotal"`
	TaxTotal  int64  `json:"tax_total"`
	Total     int64  `json:"total"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateInvoiceTotals(ctx context.Context, arg UpdateInvoiceTotalsParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoiceTotals,
		arg.Subtotal,
		arg.TaxTotal,
		arg.Total,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
