// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice_items.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const createInvoiceItem = `-- name: CreateInvoiceItem :exec
INSERT INTO invoice_items (id, invoice_id, product_id, description, quantity, unit_price, tax_id, tax_rate, amount, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInvoiceItemParams struct {
	ID          string         `json:"id"`
	InvoiceID   string         `json:"invoice_id"`
	ProductID   sql.NullString `json:"product_id"`
	Description string         `json:"description"`
	Quantity    float64        `json:"quantity"`
	UnitPrice   int64          `json:"unit_price"`
	TaxID       sql.NullString `json:"tax_id"`
	TaxRate     float64        `json:"tax_rate"`
	Amount      int64          `json:"amount"`
	SortOrder   int64          `json:"sort_order"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) error {
	_, err := q.db.ExecContext(ctx, createInvoiceItem,
		arg.ID,
		arg.InvoiceID,
		arg.ProductID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.TaxID,
		arg.TaxRate,
		arg.Amount,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const deleteInvoiceItem = `-- name: DeleteInvoiceItem :exec
DELETE FROM invoice_items WHERE id = ?
`

func (q *Queries) DeleteInvoiceItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvoiceItem, id)
	return err
}

const deleteInvoiceItemsByInvoice = `-- name: DeleteInvoiceItemsByInvoice :exec
DELETE FROM invoice_items WHERE invoice_id = ?
`

func (q *Queries) DeleteInvoiceItemsByInvoice(ctx context.Context, invoiceID string) error {
	_, err := q.db.ExecContext(ctx, deleteInvoiceItemsByInvoice, invoiceID)
	return err
}

const getInvoiceItem = `-- name: GetInvoiceItem :one
SELECT id, invoice_id, product_id, description, quantity, unit_price, tax_id, tax_rate, amount, sort_order, created_at FROM invoice_items WHERE id = ?
`

func (q *Queries) GetInvoiceItem(ctx context.Context, id string) (InvoiceItem, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceItem, id)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProductID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.TaxID,
		&i.TaxRate,
		&i.Amount,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, product_id, description, quantity, unit_price, tax_id, tax_rate, amount, sort_order, created_at FROM invoice_items WHERE invoice_id = ? ORDER BY sort_order ASC
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID string) ([]InvoiceItem, error) {
	rows, err := q.db.QueryContext(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ProductID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.TaxID,
			&i.TaxRate,
			&i.Amount,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
