// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package dbsqlc

import (
	"context"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (id, invoice_id, amount, method, reference, paid_at, notes, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePaymentParams struct {
	ID        string `json:"id"`
	InvoiceID string `json:"invoice_id"`
	Amount    int64  `json:"amount"`
	Method    string `json:"method"`
	Reference string `json:"reference"`
	PaidAt    string `json:"paid_at"`
	Notes     string `json:"notes"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.InvoiceID,
		arg.Amount,
		arg.Method,
		arg.Reference,
		arg.PaidAt,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments WHERE id = ?
`

func (q *Queries) DeletePayment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePayment, id)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, invoice_id, amount, method, reference, paid_at, notes, created_at FROM payments WHERE id = ?
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Amount,
		&i.Method,
		&i.Reference,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, invoice_id, amount, method, reference, paid_at, notes, created_at FROM payments WHERE invoice_id = ? ORDER BY paid_at DESC
`

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, invoiceID string) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Amount,
			&i.Method,
			&i.Reference,
			&i.PaidAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPaymentsByInvoice = `-- name: SumPaymentsByInvoice :one
SELECT CAST(COALESCE(SUM(amount), 0) AS INTEGER) AS total_paid FROM payments WHERE invoice_id = ?
`

func (q *Queries) SumPaymentsByInvoice(ctx context.Context, invoiceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumPaymentsByInvoice, invoiceID)
	var total_paid int64
	err := row.Scan(&total_paid)
	return total_paid, err
}
