// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const createRecurringInvoice = `-- name: CreateRecurringInvoice :exec
INSERT INTO recurring_invoices (id, client_id, schedule, status, next_run, last_run, currency, template_id, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRecurringInvoiceParams struct {
	ID         string `json:"id"`
	ClientID   string `json:"client_id"`
	Schedule   string `json:"schedule"`
	Status     string `json:"status"`
	NextRun    string `json:"next_run"`
	LastRun    string `json:"last_run"`
	Currency   string `json:"currency"`
	TemplateID string `json:"template_id"`
	Notes      string `json:"notes"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) CreateRecurringInvoice(ctx context.Context, arg CreateRecurringInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, createRecurringInvoice,
		arg.ID,
		arg.ClientID,
		arg.Schedule,
		arg.Status,
		arg.NextRun,
		arg.LastRun,
		arg.Currency,
		arg.TemplateID,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRecurringInvoiceItem = `-- name: CreateRecurringInvoiceItem :exec
INSERT INTO recurring_invoice_items (id, recurring_invoice_id, product_id, description, quantity, unit_price, tax_id, tax_rate, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRecurringInvoiceItemParams struct {
	ID                 string         `json:"id"`
	RecurringInvoiceID string         `json:"recurring_invoice_id"`
	ProductID          sql.NullString `json:"product_id"`
	Description        string         `json:"description"`
	Quantity           float64        `json:"quantity"`
	UnitPrice          int64          `json:"unit_price"`
	TaxID              sql.NullString `json:"tax_id"`
	TaxRate            float64        `json:"tax_rate"`
	SortOrder          int64          `json:"sort_order"`
	CreatedAt          string         `json:"created_at"`
}

func (q *Queries) CreateRecurringInvoiceItem(ctx context.Context, arg CreateRecurringInvoiceItemParams) error {
	_, err := q.db.ExecContext(ctx, createRecurringInvoiceItem,
		arg.ID,
		arg.RecurringInvoiceID,
		arg.ProductID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.TaxID,
		arg.TaxRate,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const deleteRecurringInvoice = `-- name: DeleteRecurringInvoice :exec
DELETE FROM recurring_invoices WHERE id = ?
`

func (q *Queries) DeleteRecurringInvoice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecurringInvoice, id)
	return err
}

const deleteRecurringInvoiceItems = `-- name: DeleteRecurringInvoiceItems :exec
DELETE FROM recurring_invoice_items WHERE recurring_invoice_id = ?
`

func (q *Queries) DeleteRecurringInvoiceItems(ctx context.Context, recurringInvoiceID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecurringInvoiceItems, recurringInvoiceID)
	return err
}

const getRecurringInvoice = `-- name: GetRecurringInvoice :one
SELECT id, client_id, schedule, status, next_run, last_run, currency, template_id, notes, created_at, updated_at FROM recurring_invoices WHERE id = ?
`

func (q *Queries) GetRecurringInvoice(ctx context.Context, id string) (RecurringInvoice, error) {
	row := q.db.QueryRowContext(ctx, getRecurringInvoice, id)
	var i RecurringInvoice
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Schedule,
		&i.Status,
		&i.NextRun,
		&i.LastRun,
		&i.Currency,
		&i.TemplateID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRecurringInvoices = `-- name: ListDueRecurringInvoices :many
SELECT id, client_id, schedule, status, next_run, last_run, currency, template_id, notes, created_at, updated_at FROM recurring_invoices WHERE status = 'active' AND next_run <= ? ORDER BY next_run ASC
`

func (q *Queries) ListDueRecurringInvoices(ctx context.Context, nextRun string) ([]RecurringInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listDueRecurringInvoices, nextRun)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringInvoice{}
	for rows.Next() {
		var i RecurringInvoice
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Schedule,
			&i.Status,
			&i.NextRun,
			&i.LastRun,
			&i.Currency,
			&i.TemplateID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringInvoiceItems = `-- name: ListRecurringInvoiceItems :many
SELECT id, recurring_invoice_id, product_id, description, quantity, unit_price, tax_id, tax_rate, sort_order, created_at FROM recurring_invoice_items WHERE recurring_invoice_id = ? ORDER BY sort_order ASC
`

func (q *Queries) ListRecurringInvoiceItems(ctx context.Context, recurringInvoiceID string) ([]RecurringInvoiceItem, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringInvoiceItems, recurringInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringInvoiceItem{}
	for rows.Next() {
		var i RecurringInvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.RecurringInvoiceID,
			&i.ProductID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.TaxID,
			&i.TaxRate,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringInvoices = `-- name: ListRecurringInvoices :many
SELECT id, client_id, schedule, status, next_run, last_run, currency, template_id, notes, created_at, updated_at FROM recurring_invoices ORDER BY created_at DESC
`

func (q *Queries) ListRecurringInvoices(ctx context.Context) ([]RecurringInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringInvoice{}
	for rows.Next() {
		var i RecurringInvoice
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Schedule,
			&i.Status,
			&i.NextRun,
			&i.LastRun,
			&i.Currency,
			&i.TemplateID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringInvoiceNextRun = `-- name: UpdateRecurringInvoiceNextRun :exec
UPDATE recurring_invoices SET next_run = ?, last_run = ?, updated_at = ? WHERE id = ?
`

type UpdateRecurringInvoiceNextRunParams struct {
	NextRun   string `json:"next_run"`
	LastRun   string `json:"last_run"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateRecurringInvoiceNextRun(ctx context.Context, arg UpdateRecurringInvoiceNextRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRecurringInvoiceNextRun,
		arg.NextRun,
		arg.LastRun,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateRecurringInvoiceStatus = `-- name: UpdateRecurringInvoiceStatus :exec
UPDATE recurring_invoices SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateRecurringInvoiceStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateRecurringInvoiceStatus(ctx context.Context, arg UpdateRecurringInvoiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRecurringInvoiceStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
