// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package dbsqlc

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, company_name, company_email, company_phone, company_address, invoice_prefix, next_invoice_number, default_due_days, default_currency, default_template_id, created_at, updated_at FROM settings WHERE id = 'default'
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyEmail,
		&i.CompanyPhone,
		&i.CompanyAddress,
		&i.InvoicePrefix,
		&i.NextInvoiceNumber,
		&i.DefaultDueDays,
		&i.DefaultCurrency,
		&i.DefaultTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInvoiceNumber = `-- name: IncrementInvoiceNumber :one
UPDATE settings SET next_invoice_number = next_invoice_number + 1, updated_at = ?
WHERE id = 'default'
RETURNING next_invoice_number - 1
`

func (q *Queries) IncrementInvoiceNumber(ctx context.Context, updatedAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementInvoiceNumber, updatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings SET
    company_name = ?,
    company_email = ?,
    company_phone = ?,
    company_address = ?,
    invoice_prefix = ?,
    next_invoice_number = ?,
    default_due_days = ?,
    default_currency = ?,
    default_template_id = ?,
    updated_at = ?
WHERE id = 'default'
`

type UpdateSettingsParams struct {
	CompanyName       string `json:"company_name"`
	CompanyEmail      string `json:"company_email"`
	CompanyPhone      string `json:"company_phone"`
	CompanyAddress    string `json:"company_address"`
	InvoicePrefix     string `json:"invoice_prefix"`
	NextInvoiceNumber int64  `json:"next_invoice_number"`
	DefaultDueDays    int64  `json:"default_due_days"`
	DefaultCurrency   string `json:"default_currency"`
	DefaultTemplateID string `json:"default_template_id"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings,
		arg.CompanyName,
		arg.CompanyEmail,
		arg.CompanyPhone,
		arg.CompanyAddress,
		arg.InvoicePrefix,
		arg.NextInvoiceNumber,
		arg.DefaultDueDays,
		arg.DefaultCurrency,
		arg.DefaultTemplateID,
		arg.UpdatedAt,
	)
	return err
}
