// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taxes.sql

package dbsqlc

import (
	"context"
)

const createTax = `-- name: CreateTax :exec
INSERT INTO taxes (id, name, rate, is_default, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTaxParams struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Rate      float64 `json:"rate"`
	IsDefault int64   `json:"is_default"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) CreateTax(ctx context.Context, arg CreateTaxParams) error {
	_, err := q.db.ExecContext(ctx, createTax,
		arg.ID,
		arg.Name,
		arg.Rate,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTax = `-- name: DeleteTax :exec
DELETE FROM taxes WHERE id = ?
`

func (q *Queries) DeleteTax(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTax, id)
	return err
}

const getDefaultTax = `-- name: GetDefaultTax :one
SELECT id, name, rate, is_default, created_at, updated_at FROM taxes WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultTax(ctx context.Context) (Tax, error) {
	row := q.db.QueryRowContext(ctx, getDefaultTax)
	var i Tax
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rate,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTax = `-- name: GetTax :one
SELECT id, name, rate, is_default, created_at, updated_at FROM taxes WHERE id = ?
`

func (q *Queries) GetTax(ctx context.Context, id string) (Tax, error) {
	row := q.db.QueryRowContext(ctx, getTax, id)
	var i Tax
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rate,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaxes = `-- name: ListTaxes :many
SELECT id, name, rate, is_default, created_at, updated_at FROM taxes ORDER BY name ASC
`

func (q *Queries) ListTaxes(ctx context.Context) ([]Tax, error) {
	rows, err := q.db.QueryContext(ctx, listTaxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tax{}
	for rows.Next() {
		var i Tax
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rate,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTax = `-- name: UpdateTax :exec
UPDATE taxes SET name = ?, rate = ?, is_default = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaxParams struct {
	Name      string  `json:"name"`
	Rate      float64 `json:"rate"`
	IsDefault int64   `json:"is_default"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateTax(ctx context.Context, arg UpdateTaxParams) error {
	_, err := q.db.ExecContext(ctx, updateTax,
		arg.Name,
		arg.Rate,
		arg.IsDefault,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
