// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package dbsqlc

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :exec
INSERT INTO invoice_templates (id, name, path, is_default, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTemplateParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	IsDefault int64  `json:"is_default"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM invoice_templates WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const getDefaultTemplate = `-- name: GetDefaultTemplate :one
SELECT id, name, path, is_default, created_at, updated_at FROM invoice_templates WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultTemplate(ctx context.Context) (InvoiceTemplate, error) {
	row := q.db.QueryRowContext(ctx, getDefaultTemplate)
	var i InvoiceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, path, is_default, created_at, updated_at FROM invoice_templates WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (InvoiceTemplate, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i InvoiceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByPath = `-- name: GetTemplateByPath :one
SELECT id, name, path, is_default, created_at, updated_at FROM invoice_templates WHERE path = ?
`

func (q *Queries) GetTemplateByPath(ctx context.Context, path string) (InvoiceTemplate, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByPath, path)
	var i InvoiceTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, path, is_default, created_at, updated_at FROM invoice_templates ORDER BY name ASC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]InvoiceTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceTemplate{}
	for rows.Next() {
		var i InvoiceTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE invoice_templates SET name = ?, path = ?, is_default = ?, updated_at = ?
WHERE id = ?
`

type UpdateTemplateParams struct {
	Name      string `json:"name"`
	Path      string `json:"path"`
	IsDefault int64  `json:"is_default"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Name,
		arg.Path,
		arg.IsDefault,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
